name: flutter_svg
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
homepage: https://github.com/dnfield/flutter_svg
version: 0.19.2+1

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path_drawing: ^0.5.1
  vector_math: ^2.1.0

  xml: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  path: ^1.8.0
  test: ^1.16.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.24.0-6.0.pre"
